[package]
name = "gw-ws"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-nats.workspace = true
axum.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
sarvex-runtime = { path = "../crates/sarvex-runtime" }
sarvex-auth = { path = "../crates/sarvex-auth" }
sarvex-me-client = { path = "../crates/sarvex-me-client" }
