INSERT INTO ledger.accounts (account_code, account_type, currency, user_id) VALUES
  ('ASSET:HOUSE:WALLET', 'ASSET', 'USDC', NULL),
  ('LIAB:UNALLOCATED_DEPOSIT', 'LIABILITY', 'USDC', NULL),
  ('REVENUE:FEES:TAKER', 'REVENUE', 'USDC', NULL),
  ('REVENUE:FEES:MAKER', 'REVENUE', 'USDC', NULL),
  ('REVENUE:SETTLEMENT_ROUNDING', 'REVENUE', 'USDC', NULL),
  ('LIAB:HOUSE:UNSETTLED_TRADES:RBI-JUN26-CUT25', 'LIABILITY', 'USDC', NULL),
  ('LIAB:HOUSE:UNSETTLED_TRADES:INDIA-CPI-JUN26-SCALAR', 'LIABILITY', 'USDC', NULL)
ON CONFLICT (account_code) DO NOTHING;
