[package]
name = "position-svc"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-nats.workspace = true
axum.workspace = true
chrono.workspace = true
futures-util.workspace = true
prost-types.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
sarvex-contracts = { path = "../crates/sarvex-contracts" }
sarvex-db = { path = "../crates/sarvex-db" }
sarvex-runtime = { path = "../crates/sarvex-runtime" }
