[package]
name = "marketdata-svc"
version.workspace = true
edition.workspace = true

[dependencies]
async-nats.workspace = true
chrono.workspace = true
futures-util.workspace = true
prost-types.workspace = true
serde_json.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
anyhow.workspace = true
sarvex-contracts = { path = "../crates/sarvex-contracts" }
sarvex-events = { path = "../crates/sarvex-events" }
sarvex-runtime = { path = "../crates/sarvex-runtime" }
