DROP SEQUENCE IF EXISTS audit.event_seq_gen;

DROP TABLE IF EXISTS audit.events;
DROP TABLE IF EXISTS settlement.settlement_payouts;
DROP TABLE IF EXISTS settlement.settlements;
DROP TABLE IF EXISTS oracle.oracle_keys;
DROP TABLE IF EXISTS oracle.resolutions;
DROP TABLE IF EXISTS oracle.attestations;
DROP TABLE IF EXISTS position.open_interest;
DROP TABLE IF EXISTS position.consumer_offsets;
DROP TABLE IF EXISTS position.applied_fills;
DROP TABLE IF EXISTS position.position_history;
DROP TABLE IF EXISTS position.positions;
DROP TABLE IF EXISTS risk.working_orders_summary;
DROP TABLE IF EXISTS risk.contract_position_limits;
DROP TABLE IF EXISTS risk.user_limits;
DROP TABLE IF EXISTS orders.fill_posting_outbox;
DROP TABLE IF EXISTS orders.fills;
DROP TABLE IF EXISTS orders.orders;
DROP VIEW IF EXISTS ledger.user_balances;
DROP TABLE IF EXISTS ledger.hold_operations;
DROP TABLE IF EXISTS ledger.holds;
DROP TRIGGER IF EXISTS trg_block_entries_delete ON ledger.entries;
DROP TRIGGER IF EXISTS trg_block_entries_update ON ledger.entries;
DROP TRIGGER IF EXISTS trg_assert_tx_balanced ON ledger.entries;
DROP FUNCTION IF EXISTS ledger.block_entries_update_delete();
DROP FUNCTION IF EXISTS ledger.assert_tx_balanced();
DROP TABLE IF EXISTS ledger.ledger_event_outbox;
DROP TABLE IF EXISTS ledger.entries;
DROP TABLE IF EXISTS ledger.transactions;
DROP TABLE IF EXISTS ledger.accounts;
DROP TABLE IF EXISTS users.api_keys;
DROP TABLE IF EXISTS users.users;
DROP TABLE IF EXISTS refdata.contract_state_history;
DROP TABLE IF EXISTS refdata.contracts;
DROP TABLE IF EXISTS refdata.events;
DROP TABLE IF EXISTS refdata.series;

DROP TYPE IF EXISTS oracle.resolution_status;
DROP TYPE IF EXISTS orders.order_status;
DROP TYPE IF EXISTS orders.time_in_force;
DROP TYPE IF EXISTS orders.order_action;
DROP TYPE IF EXISTS orders.order_side;
DROP TYPE IF EXISTS ledger.account_type;
DROP TYPE IF EXISTS refdata.contract_state;
DROP TYPE IF EXISTS refdata.contract_kind;

DROP SCHEMA IF EXISTS audit;
DROP SCHEMA IF EXISTS settlement;
DROP SCHEMA IF EXISTS oracle;
DROP SCHEMA IF EXISTS position;
DROP SCHEMA IF EXISTS risk;
DROP SCHEMA IF EXISTS orders;
DROP SCHEMA IF EXISTS ledger;
DROP SCHEMA IF EXISTS users;
DROP SCHEMA IF EXISTS refdata;
